services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    restart: unless-stopped
    environment:
      - SEARXNG_PORT=8100
      - SEARXNG_BASE_URL=http://172.17.0.1:8100/
    volumes:
      - ./searxng/settings.yml:/etc/searxng/settings.yml:ro
      - ./searxng/limiter.toml:/etc/searxng/limiter.toml:ro
    ports:
      - "172.17.0.1:8100:8100" # ip address obtained from `ip addr show docker0 | grep inet`
